Repository NativeScript/plugins, pull requests merged in 2020-10, with the labels that each got.

#18 feat(animated-circle): add properties for UX functionality
  packages/animated-circle/common.ts
  packages/animated-circle/index.android.ts
  packages/animated-circle/index.ios.ts
  packages/animated-circle/package.json
Labels: cla: yes

#21 Bug: remove the text size setting on auto-fit-text in constructor
  packages/auto-fit-text/index.android.ts
  packages/auto-fit-text/package.json
Labels: bug

#22 FIX NativeScript/nativescript-datetimepicker#78
  packages/datetimepicker/index.ios.ts
Labels: cla: yes

#24 chore(local-notifications): update readme and format files
  packages/local-notifications/README.md
  packages/local-notifications/common.ts
  packages/local-notifications/index.android.ts
  packages/local-notifications/index.ios.ts
  packages/local-notifications/package.json
Labels: cla: yes, documentation

#26 feat(local-notifications): add number to interval options
  packages/local-notifications/README.md
  packages/local-notifications/common.ts
  packages/local-notifications/index.android.ts
  packages/local-notifications/index.d.ts
  packages/local-notifications/index.ios.ts
Labels: cla: yes, enhancement

#28 fix for sharing images on ios with @nativescript/social-share
  packages/social-share/index.ios.ts
Labels: cla: yes

#23 Add Detox plugin
  README.md
  nx.json
  packages/detox/README.md
  packages/detox/package.json
  packages/detox/platforms/android/AndroidManifest.xml
  packages/detox/platforms/android/androidTest/java/com/tns/DetoxTest.java
  packages/detox/platforms/android/androidTest/java/com/tns/DetoxTestRunner.java
  packages/detox/platforms/android/include.gradle
  packages/detox/postinstall.js
  packages/detox/preuninstall.js
  packages/detox/references.d.ts
  packages/detox/scripts/detox-build.js
  packages/detox/scripts/enable-animations.js
  packages/detox/tsconfig.json
  tools/workspace-scripts.js
  workspace.json
Labels: cla: yes

#32 Minor correction on 'localize' README.
  packages/localize/README.md
Labels: cla: yes

#36 fix:(animated-circle) color properties
  packages/animated-circle/index.android.ts
  packages/animated-circle/package.json
Labels: cla: yes

#37 fix:(animated-circle) improve native setting for android
  packages/animated-circle/index.android.ts
  packages/animated-circle/index.ios.ts
  packages/animated-circle/package.json
Labels: cla: yes

#38 fix:(animated-circle) crash when setting clockwise boolean value
  packages/animated-circle/index.ios.ts
  packages/animated-circle/package.json
Labels: cla: yes
